# Analyze error patterns from git history
# Part of self-improvement skill (PowerShell version)

param(
    [int]$Days = 30
)

$ErrorActionPreference = "Continue"

# Configuration
$outputDir = ".claude/analysis"
$timestamp = Get-Date -Format "yyyy-MM-dd"

Write-Host ""
Write-Host "======================================="
Write-Host "  Error Pattern Analysis"
Write-Host "======================================="
Write-Host ""
Write-Host "Period: Last $Days days"
Write-Host "Output: $outputDir/errors-$timestamp.md"
Write-Host ""

# Create output directory
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

# Start report
$report = "$outputDir/errors-$timestamp.md"

# Calculate date for git log
$sinceDate = (Get-Date).AddDays(-$Days).ToString("yyyy-MM-dd")

# Initialize report
@"
# Error Pattern Analysis

**Date:** $timestamp
**Period:** Last $Days days
**Generated by:** self-improvement skill

---

"@ | Out-File -FilePath $report -Encoding UTF8

# 1. Find all fix commits
Write-Host "Analyzing fix commits..."
$fixCommits = git log --since="$Days days ago" --grep="^fix" --oneline 2>$null
$fixCount = ($fixCommits | Measure-Object -Line).Lines

@"
## Summary

- **Fix commits:** $fixCount
- **Period:** $Days days
- **Rate:** $('{0:N1}' -f ($fixCount / $Days)) fixes/day

---

## Fix Commits Detail

"@ | Out-File -FilePath $report -Append -Encoding UTF8

# Get detailed fix commits
$fixDetails = git log --since="$Days days ago" --grep="^fix" --format="### %s%n%n**Commit:** %h%n**Date:** %ad%n**Author:** %an%n%n%b%n---" --date=short 2>$null
if ($fixDetails) {
    $fixDetails | Out-File -FilePath $report -Append -Encoding UTF8
}

# 2. Categorize errors
Write-Host "Categorizing errors..."

@"

---

## Error Categories

"@ | Out-File -FilePath $report -Append -Encoding UTF8

# PowerShell errors
$psErrors = git log --since="$Days days ago" --grep="PowerShell|\.ps1" --oneline 2>$null
$psErrorCount = if ($psErrors) { ($psErrors | Measure-Object -Line).Lines } else { 0 }

@"
### PowerShell Issues: $psErrorCount

"@ | Out-File -FilePath $report -Append -Encoding UTF8

if ($psErrorCount -gt 0) {
    $psErrors | Out-File -FilePath $report -Append -Encoding UTF8
}

# Encoding issues
$encodingErrors = git log --since="$Days days ago" --grep="encoding|emoji|character" --oneline 2>$null
$encodingCount = if ($encodingErrors) { ($encodingErrors | Measure-Object -Line).Lines } else { 0 }

@"

### Encoding Issues: $encodingCount

"@ | Out-File -FilePath $report -Append -Encoding UTF8

if ($encodingCount -gt 0) {
    $encodingErrors | Out-File -FilePath $report -Append -Encoding UTF8
}

# Quote/Syntax errors
$quoteErrors = git log --since="$Days days ago" --grep="quote|syntax|escap" --oneline 2>$null
$quoteCount = if ($quoteErrors) { ($quoteErrors | Measure-Object -Line).Lines } else { 0 }

@"

### Quote/Syntax Errors: $quoteCount

"@ | Out-File -FilePath $report -Append -Encoding UTF8

if ($quoteCount -gt 0) {
    $quoteErrors | Out-File -FilePath $report -Append -Encoding UTF8
}

# Validation errors
$validationErrors = git log --since="$Days days ago" --grep="validat|check.*fail" --oneline 2>$null
$validationCount = if ($validationErrors) { ($validationErrors | Measure-Object -Line).Lines } else { 0 }

@"

### Validation Errors: $validationCount

"@ | Out-File -FilePath $report -Append -Encoding UTF8

if ($validationCount -gt 0) {
    $validationErrors | Out-File -FilePath $report -Append -Encoding UTF8
}

# Build errors
$buildErrors = git log --since="$Days days ago" --grep="build.*fail|build.*error" --oneline 2>$null
$buildCount = if ($buildErrors) { ($buildErrors | Measure-Object -Line).Lines } else { 0 }

@"

### Build Errors: $buildCount

"@ | Out-File -FilePath $report -Append -Encoding UTF8

if ($buildCount -gt 0) {
    $buildErrors | Out-File -FilePath $report -Append -Encoding UTF8
}

# 3. Recurring patterns
Write-Host "Detecting recurring patterns..."

@"

---

## Recurring Patterns

### Most Common Keywords in Fixes

"@ | Out-File -FilePath $report -Append -Encoding UTF8

# Extract keywords from fix commits
$fixMessages = git log --since="$Days days ago" --grep="^fix" --format="%s" 2>$null
if ($fixMessages) {
    $keywords = $fixMessages | Select-String -Pattern 'PowerShell|quote|emoji|encoding|syntax|validation|build|commit|hook|CI' -AllMatches |
        ForEach-Object { $_.Matches } |
        ForEach-Object { $_.Value } |
        Group-Object |
        Sort-Object Count -Descending |
        ForEach-Object { "  $($_.Count) - $($_.Name)" }

    if ($keywords) {
        @"
``````
$($keywords -join "`n")
``````

"@ | Out-File -FilePath $report -Append -Encoding UTF8
    }
}

# 4. Recommendations
Write-Host "Generating recommendations..."

@"

---

## Recommendations

Based on the analysis:

"@ | Out-File -FilePath $report -Append -Encoding UTF8

# Check if PowerShell is a problem
if ($psErrorCount -gt 2) {
    @"
### [ERROR] High Priority: PowerShell Issues

**Finding:** $psErrorCount PowerShell-related fixes in $Days days

**Recommendation:**
1. Review PowerShell guidelines in CLAUDE.md
2. Consider extracting to .claude/guides/platform/powershell.md
3. Add PowerShell-specific testing before commits
4. Create PowerShell best practices checklist

"@ | Out-File -FilePath $report -Append -Encoding UTF8
}

# Check for high fix rate
$threshold = [math]::Floor($Days / 3)
if ($fixCount -gt $threshold) {
    @"
### [WARNING] Warning: High Fix Rate

**Finding:** Averaging $('{0:N1}' -f ($fixCount / $Days)) fixes/day

**Recommendation:**
1. Review why errors are frequent
2. Add more preventive guidelines
3. Consider pre-commit validation
4. Update skills with learnings

"@ | Out-File -FilePath $report -Append -Encoding UTF8
}

# General recommendations
$nextReview = (Get-Date).AddDays(30).ToString("yyyy-MM-dd")

@"
### [SUCCESS] Always Recommended

1. **Update Error Catalog**
   - Add new patterns to self-improvement skill
   - Document in .claude/guides/troubleshooting/

2. **Review CLAUDE.md**
   - Ensure fixes are documented
   - Add prevention guidelines
   - Update best practices

3. **Enhance Skills**
   - commit-helper: Update with commit patterns
   - github-issues: Improve validation searches
   - self-improvement: Add to error catalog

4. **Track Metrics**
   - Monitor error recurrence
   - Measure prevention success
   - Review quarterly

---

## Action Items

- [ ] Review error patterns above
- [ ] Update CLAUDE.md with new learnings
- [ ] Enhance relevant skills
- [ ] Add to error catalog
- [ ] Create prevention guidelines
- [ ] Test improvements
- [ ] Schedule next review ($nextReview)

---

**Next Steps:**
1. Review this report
2. Implement high-priority recommendations
3. Update documentation
4. Commit improvements
5. Monitor for recurrence

"@ | Out-File -FilePath $report -Append -Encoding UTF8

# Display summary
Write-Host ""
Write-Host "[SUCCESS] Analysis complete!"
Write-Host ""
Write-Host "Summary:"
Write-Host "  - Fix commits: $fixCount"
Write-Host "  - PowerShell issues: $psErrorCount"
Write-Host "  - Rate: $('{0:N1}' -f ($fixCount / $Days)) fixes/day"
Write-Host ""
Write-Host "Report saved to: $report"
Write-Host ""

# Preview
Write-Host "Preview:"
Write-Host "======================================="
Get-Content $report | Select-Object -First 30
Write-Host "..."
Write-Host "======================================="
Write-Host ""
Write-Host "Full report: $report"
Write-Host ""
