#!/bin/bash
# Analyze error patterns from git history
# Part of self-improvement skill

set -e

# Configuration
DAYS=${1:-30}  # Default to last 30 days
OUTPUT_DIR=".claude/analysis"
TIMESTAMP=$(date +%Y-%m-%d)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
echo "======================================="
echo "  Error Pattern Analysis"
echo "======================================="
echo ""
echo "Period: Last $DAYS days"
echo "Output: $OUTPUT_DIR/errors-$TIMESTAMP.md"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Start report
REPORT="$OUTPUT_DIR/errors-$TIMESTAMP.md"

cat > "$REPORT" << EOF
# Error Pattern Analysis

**Date:** $TIMESTAMP
**Period:** Last $DAYS days
**Generated by:** self-improvement skill

---

EOF

# 1. Find all fix commits
echo "Analyzing fix commits..."
FIX_COMMITS=$(git log --since="$DAYS days ago" --grep="^fix" --oneline | wc -l)

cat >> "$REPORT" << EOF
## Summary

- **Fix commits:** $FIX_COMMITS
- **Period:** $DAYS days
- **Rate:** $(echo "scale=1; $FIX_COMMITS / $DAYS" | bc) fixes/day

---

## Fix Commits Detail

EOF

git log --since="$DAYS days ago" --grep="^fix" --format="### %s%n%n**Commit:** %h%n**Date:** %ad%n**Author:** %an%n%n%b%n---" --date=short >> "$REPORT"

# 2. Categorize errors
echo "Categorizing errors..."

cat >> "$REPORT" << EOF

---

## Error Categories

EOF

# PowerShell errors
PS_ERRORS=$(git log --since="$DAYS days ago" --grep="PowerShell\|\.ps1" --oneline | wc -l)
cat >> "$REPORT" << EOF
### PowerShell Issues: $PS_ERRORS
EOF
if [ $PS_ERRORS -gt 0 ]; then
    git log --since="$DAYS days ago" --grep="PowerShell\|\.ps1" --oneline >> "$REPORT"
fi

cat >> "$REPORT" << EOF

### Encoding Issues: $(git log --since="$DAYS days ago" --grep="encoding\|emoji\|character" --oneline | wc -l)
EOF
git log --since="$DAYS days ago" --grep="encoding\|emoji\|character" --oneline >> "$REPORT" || true

cat >> "$REPORT" << EOF

### Quote/Syntax Errors: $(git log --since="$DAYS days ago" --grep="quote\|syntax\|escap" --oneline | wc -l)
EOF
git log --since="$DAYS days ago" --grep="quote\|syntax\|escap" --oneline >> "$REPORT" || true

cat >> "$REPORT" << EOF

### Validation Errors: $(git log --since="$DAYS days ago" --grep="validat\|check.*fail" --oneline | wc -l)
EOF
git log --since="$DAYS days ago" --grep="validat\|check.*fail" --oneline >> "$REPORT" || true

cat >> "$REPORT" << EOF

### Build Errors: $(git log --since="$DAYS days ago" --grep="build.*fail\|build.*error" --oneline | wc -l)
EOF
git log --since="$DAYS days ago" --grep="build.*fail\|build.*error" --oneline >> "$REPORT" || true

# 3. Recurring patterns
echo "Detecting recurring patterns..."

cat >> "$REPORT" << EOF

---

## Recurring Patterns

EOF

# Check for repeated keywords in fix commits
echo "Analyzing common keywords in fix commits..."
KEYWORDS=$(git log --since="$DAYS days ago" --grep="^fix" --format="%s" | \
    grep -oE 'PowerShell|quote|emoji|encoding|syntax|validation|build|commit|hook|CI' | \
    sort | uniq -c | sort -rn)

cat >> "$REPORT" << EOF
### Most Common Keywords in Fixes

\`\`\`
$KEYWORDS
\`\`\`

EOF

# 4. Recommendations
echo "Generating recommendations..."

cat >> "$REPORT" << EOF

---

## Recommendations

Based on the analysis:

EOF

# Check if PowerShell is a problem
if [ $PS_ERRORS -gt 2 ]; then
    cat >> "$REPORT" << EOF
### 🔴 High Priority: PowerShell Issues

**Finding:** $PS_ERRORS PowerShell-related fixes in $DAYS days

**Recommendation:**
1. Review PowerShell guidelines in CLAUDE.md
2. Consider extracting to .claude/guides/platform/powershell.md
3. Add PowerShell-specific testing before commits
4. Create PowerShell best practices checklist

EOF
fi

# Check for high fix rate
if [ $(echo "$FIX_COMMITS > $(($DAYS / 3))" | bc) -eq 1 ]; then
    cat >> "$REPORT" << EOF
### ⚠️  Warning: High Fix Rate

**Finding:** Averaging $(echo "scale=1; $FIX_COMMITS / $DAYS" | bc) fixes/day

**Recommendation:**
1. Review why errors are frequent
2. Add more preventive guidelines
3. Consider pre-commit validation
4. Update skills with learnings

EOF
fi

# General recommendations
cat >> "$REPORT" << EOF
### ✅ Always Recommended

1. **Update Error Catalog**
   - Add new patterns to self-improvement skill
   - Document in .claude/guides/troubleshooting/

2. **Review CLAUDE.md**
   - Ensure fixes are documented
   - Add prevention guidelines
   - Update best practices

3. **Enhance Skills**
   - commit-helper: Update with commit patterns
   - github-issues: Improve validation searches
   - self-improvement: Add to error catalog

4. **Track Metrics**
   - Monitor error recurrence
   - Measure prevention success
   - Review quarterly

EOF

# 5. Action items
cat >> "$REPORT" << EOF

---

## Action Items

- [ ] Review error patterns above
- [ ] Update CLAUDE.md with new learnings
- [ ] Enhance relevant skills
- [ ] Add to error catalog
- [ ] Create prevention guidelines
- [ ] Test improvements
- [ ] Schedule next review ($(date -d "+30 days" +%Y-%m-%d))

---

**Next Steps:**
1. Review this report
2. Implement high-priority recommendations
3. Update documentation
4. Commit improvements
5. Monitor for recurrence

EOF

# Display summary
echo ""
echo "✅ Analysis complete!"
echo ""
echo "Summary:"
echo "  - Fix commits: $FIX_COMMITS"
echo "  - PowerShell issues: $PS_ERRORS"
echo "  - Rate: $(echo "scale=1; $FIX_COMMITS / $DAYS" | bc) fixes/day"
echo ""
echo "Report saved to: $REPORT"
echo ""

# Optionally open the report
if command -v cat &> /dev/null; then
    echo "Preview:"
    echo "======================================="
    head -n 30 "$REPORT"
    echo "..."
    echo "======================================="
    echo ""
    echo "Full report: $REPORT"
fi
